/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.accumulo.core.dataImpl.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PushdownReaderRequest implements org.apache.thrift.TBase<PushdownReaderRequest, PushdownReaderRequest._Fields>, java.io.Serializable, Cloneable, Comparable<PushdownReaderRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PushdownReaderRequest");

  private static final org.apache.thrift.protocol.TField READER_CLASS_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("readerClassName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField READER_CLASS_OPTIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("readerClassOptions", org.apache.thrift.protocol.TType.MAP, (short)2);
  private static final org.apache.thrift.protocol.TField PUSH_DOWN_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("pushDownList", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField PUSH_DOWN_LIST_OPTIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("pushDownListOptions", org.apache.thrift.protocol.TType.MAP, (short)4);
  private static final org.apache.thrift.protocol.TField DISABLE_CFS_ITER_FIELD_DESC = new org.apache.thrift.protocol.TField("disableCfsIter", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField DISABLE_CQS_ITER_FIELD_DESC = new org.apache.thrift.protocol.TField("disableCqsIter", org.apache.thrift.protocol.TType.BOOL, (short)6);
  private static final org.apache.thrift.protocol.TField DISABLE_VIS_ITER_FIELD_DESC = new org.apache.thrift.protocol.TField("disableVisIter", org.apache.thrift.protocol.TType.BOOL, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PushdownReaderRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PushdownReaderRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String readerClassName; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> readerClassOptions; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<IterInfo> pushDownList; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.util.Map<java.lang.String,java.lang.String>> pushDownListOptions; // required
  public boolean disableCfsIter; // required
  public boolean disableCqsIter; // required
  public boolean disableVisIter; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    READER_CLASS_NAME((short)1, "readerClassName"),
    READER_CLASS_OPTIONS((short)2, "readerClassOptions"),
    PUSH_DOWN_LIST((short)3, "pushDownList"),
    PUSH_DOWN_LIST_OPTIONS((short)4, "pushDownListOptions"),
    DISABLE_CFS_ITER((short)5, "disableCfsIter"),
    DISABLE_CQS_ITER((short)6, "disableCqsIter"),
    DISABLE_VIS_ITER((short)7, "disableVisIter");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // READER_CLASS_NAME
          return READER_CLASS_NAME;
        case 2: // READER_CLASS_OPTIONS
          return READER_CLASS_OPTIONS;
        case 3: // PUSH_DOWN_LIST
          return PUSH_DOWN_LIST;
        case 4: // PUSH_DOWN_LIST_OPTIONS
          return PUSH_DOWN_LIST_OPTIONS;
        case 5: // DISABLE_CFS_ITER
          return DISABLE_CFS_ITER;
        case 6: // DISABLE_CQS_ITER
          return DISABLE_CQS_ITER;
        case 7: // DISABLE_VIS_ITER
          return DISABLE_VIS_ITER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DISABLECFSITER_ISSET_ID = 0;
  private static final int __DISABLECQSITER_ISSET_ID = 1;
  private static final int __DISABLEVISITER_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.READER_CLASS_NAME, new org.apache.thrift.meta_data.FieldMetaData("readerClassName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.READER_CLASS_OPTIONS, new org.apache.thrift.meta_data.FieldMetaData("readerClassOptions", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.PUSH_DOWN_LIST, new org.apache.thrift.meta_data.FieldMetaData("pushDownList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, IterInfo.class))));
    tmpMap.put(_Fields.PUSH_DOWN_LIST_OPTIONS, new org.apache.thrift.meta_data.FieldMetaData("pushDownListOptions", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.DISABLE_CFS_ITER, new org.apache.thrift.meta_data.FieldMetaData("disableCfsIter", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.DISABLE_CQS_ITER, new org.apache.thrift.meta_data.FieldMetaData("disableCqsIter", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.DISABLE_VIS_ITER, new org.apache.thrift.meta_data.FieldMetaData("disableVisIter", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PushdownReaderRequest.class, metaDataMap);
  }

  public PushdownReaderRequest() {
  }

  public PushdownReaderRequest(
    java.lang.String readerClassName,
    java.util.Map<java.lang.String,java.lang.String> readerClassOptions,
    java.util.List<IterInfo> pushDownList,
    java.util.Map<java.lang.String,java.util.Map<java.lang.String,java.lang.String>> pushDownListOptions,
    boolean disableCfsIter,
    boolean disableCqsIter,
    boolean disableVisIter)
  {
    this();
    this.readerClassName = readerClassName;
    this.readerClassOptions = readerClassOptions;
    this.pushDownList = pushDownList;
    this.pushDownListOptions = pushDownListOptions;
    this.disableCfsIter = disableCfsIter;
    setDisableCfsIterIsSet(true);
    this.disableCqsIter = disableCqsIter;
    setDisableCqsIterIsSet(true);
    this.disableVisIter = disableVisIter;
    setDisableVisIterIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PushdownReaderRequest(PushdownReaderRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetReaderClassName()) {
      this.readerClassName = other.readerClassName;
    }
    if (other.isSetReaderClassOptions()) {
      java.util.Map<java.lang.String,java.lang.String> __this__readerClassOptions = new java.util.HashMap<java.lang.String,java.lang.String>(other.readerClassOptions);
      this.readerClassOptions = __this__readerClassOptions;
    }
    if (other.isSetPushDownList()) {
      java.util.List<IterInfo> __this__pushDownList = new java.util.ArrayList<IterInfo>(other.pushDownList.size());
      for (IterInfo other_element : other.pushDownList) {
        __this__pushDownList.add(new IterInfo(other_element));
      }
      this.pushDownList = __this__pushDownList;
    }
    if (other.isSetPushDownListOptions()) {
      java.util.Map<java.lang.String,java.util.Map<java.lang.String,java.lang.String>> __this__pushDownListOptions = new java.util.HashMap<java.lang.String,java.util.Map<java.lang.String,java.lang.String>>(other.pushDownListOptions.size());
      for (java.util.Map.Entry<java.lang.String, java.util.Map<java.lang.String,java.lang.String>> other_element : other.pushDownListOptions.entrySet()) {

        java.lang.String other_element_key = other_element.getKey();
        java.util.Map<java.lang.String,java.lang.String> other_element_value = other_element.getValue();

        java.lang.String __this__pushDownListOptions_copy_key = other_element_key;

        java.util.Map<java.lang.String,java.lang.String> __this__pushDownListOptions_copy_value = new java.util.HashMap<java.lang.String,java.lang.String>(other_element_value);

        __this__pushDownListOptions.put(__this__pushDownListOptions_copy_key, __this__pushDownListOptions_copy_value);
      }
      this.pushDownListOptions = __this__pushDownListOptions;
    }
    this.disableCfsIter = other.disableCfsIter;
    this.disableCqsIter = other.disableCqsIter;
    this.disableVisIter = other.disableVisIter;
  }

  @Override
  public PushdownReaderRequest deepCopy() {
    return new PushdownReaderRequest(this);
  }

  @Override
  public void clear() {
    this.readerClassName = null;
    this.readerClassOptions = null;
    this.pushDownList = null;
    this.pushDownListOptions = null;
    setDisableCfsIterIsSet(false);
    this.disableCfsIter = false;
    setDisableCqsIterIsSet(false);
    this.disableCqsIter = false;
    setDisableVisIterIsSet(false);
    this.disableVisIter = false;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getReaderClassName() {
    return this.readerClassName;
  }

  public PushdownReaderRequest setReaderClassName(@org.apache.thrift.annotation.Nullable java.lang.String readerClassName) {
    this.readerClassName = readerClassName;
    return this;
  }

  public void unsetReaderClassName() {
    this.readerClassName = null;
  }

  /** Returns true if field readerClassName is set (has been assigned a value) and false otherwise */
  public boolean isSetReaderClassName() {
    return this.readerClassName != null;
  }

  public void setReaderClassNameIsSet(boolean value) {
    if (!value) {
      this.readerClassName = null;
    }
  }

  public int getReaderClassOptionsSize() {
    return (this.readerClassOptions == null) ? 0 : this.readerClassOptions.size();
  }

  public void putToReaderClassOptions(java.lang.String key, java.lang.String val) {
    if (this.readerClassOptions == null) {
      this.readerClassOptions = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.readerClassOptions.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.String> getReaderClassOptions() {
    return this.readerClassOptions;
  }

  public PushdownReaderRequest setReaderClassOptions(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> readerClassOptions) {
    this.readerClassOptions = readerClassOptions;
    return this;
  }

  public void unsetReaderClassOptions() {
    this.readerClassOptions = null;
  }

  /** Returns true if field readerClassOptions is set (has been assigned a value) and false otherwise */
  public boolean isSetReaderClassOptions() {
    return this.readerClassOptions != null;
  }

  public void setReaderClassOptionsIsSet(boolean value) {
    if (!value) {
      this.readerClassOptions = null;
    }
  }

  public int getPushDownListSize() {
    return (this.pushDownList == null) ? 0 : this.pushDownList.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<IterInfo> getPushDownListIterator() {
    return (this.pushDownList == null) ? null : this.pushDownList.iterator();
  }

  public void addToPushDownList(IterInfo elem) {
    if (this.pushDownList == null) {
      this.pushDownList = new java.util.ArrayList<IterInfo>();
    }
    this.pushDownList.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<IterInfo> getPushDownList() {
    return this.pushDownList;
  }

  public PushdownReaderRequest setPushDownList(@org.apache.thrift.annotation.Nullable java.util.List<IterInfo> pushDownList) {
    this.pushDownList = pushDownList;
    return this;
  }

  public void unsetPushDownList() {
    this.pushDownList = null;
  }

  /** Returns true if field pushDownList is set (has been assigned a value) and false otherwise */
  public boolean isSetPushDownList() {
    return this.pushDownList != null;
  }

  public void setPushDownListIsSet(boolean value) {
    if (!value) {
      this.pushDownList = null;
    }
  }

  public int getPushDownListOptionsSize() {
    return (this.pushDownListOptions == null) ? 0 : this.pushDownListOptions.size();
  }

  public void putToPushDownListOptions(java.lang.String key, java.util.Map<java.lang.String,java.lang.String> val) {
    if (this.pushDownListOptions == null) {
      this.pushDownListOptions = new java.util.HashMap<java.lang.String,java.util.Map<java.lang.String,java.lang.String>>();
    }
    this.pushDownListOptions.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.util.Map<java.lang.String,java.lang.String>> getPushDownListOptions() {
    return this.pushDownListOptions;
  }

  public PushdownReaderRequest setPushDownListOptions(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.util.Map<java.lang.String,java.lang.String>> pushDownListOptions) {
    this.pushDownListOptions = pushDownListOptions;
    return this;
  }

  public void unsetPushDownListOptions() {
    this.pushDownListOptions = null;
  }

  /** Returns true if field pushDownListOptions is set (has been assigned a value) and false otherwise */
  public boolean isSetPushDownListOptions() {
    return this.pushDownListOptions != null;
  }

  public void setPushDownListOptionsIsSet(boolean value) {
    if (!value) {
      this.pushDownListOptions = null;
    }
  }

  public boolean isDisableCfsIter() {
    return this.disableCfsIter;
  }

  public PushdownReaderRequest setDisableCfsIter(boolean disableCfsIter) {
    this.disableCfsIter = disableCfsIter;
    setDisableCfsIterIsSet(true);
    return this;
  }

  public void unsetDisableCfsIter() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISABLECFSITER_ISSET_ID);
  }

  /** Returns true if field disableCfsIter is set (has been assigned a value) and false otherwise */
  public boolean isSetDisableCfsIter() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISABLECFSITER_ISSET_ID);
  }

  public void setDisableCfsIterIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISABLECFSITER_ISSET_ID, value);
  }

  public boolean isDisableCqsIter() {
    return this.disableCqsIter;
  }

  public PushdownReaderRequest setDisableCqsIter(boolean disableCqsIter) {
    this.disableCqsIter = disableCqsIter;
    setDisableCqsIterIsSet(true);
    return this;
  }

  public void unsetDisableCqsIter() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISABLECQSITER_ISSET_ID);
  }

  /** Returns true if field disableCqsIter is set (has been assigned a value) and false otherwise */
  public boolean isSetDisableCqsIter() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISABLECQSITER_ISSET_ID);
  }

  public void setDisableCqsIterIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISABLECQSITER_ISSET_ID, value);
  }

  public boolean isDisableVisIter() {
    return this.disableVisIter;
  }

  public PushdownReaderRequest setDisableVisIter(boolean disableVisIter) {
    this.disableVisIter = disableVisIter;
    setDisableVisIterIsSet(true);
    return this;
  }

  public void unsetDisableVisIter() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISABLEVISITER_ISSET_ID);
  }

  /** Returns true if field disableVisIter is set (has been assigned a value) and false otherwise */
  public boolean isSetDisableVisIter() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISABLEVISITER_ISSET_ID);
  }

  public void setDisableVisIterIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISABLEVISITER_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case READER_CLASS_NAME:
      if (value == null) {
        unsetReaderClassName();
      } else {
        setReaderClassName((java.lang.String)value);
      }
      break;

    case READER_CLASS_OPTIONS:
      if (value == null) {
        unsetReaderClassOptions();
      } else {
        setReaderClassOptions((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    case PUSH_DOWN_LIST:
      if (value == null) {
        unsetPushDownList();
      } else {
        setPushDownList((java.util.List<IterInfo>)value);
      }
      break;

    case PUSH_DOWN_LIST_OPTIONS:
      if (value == null) {
        unsetPushDownListOptions();
      } else {
        setPushDownListOptions((java.util.Map<java.lang.String,java.util.Map<java.lang.String,java.lang.String>>)value);
      }
      break;

    case DISABLE_CFS_ITER:
      if (value == null) {
        unsetDisableCfsIter();
      } else {
        setDisableCfsIter((java.lang.Boolean)value);
      }
      break;

    case DISABLE_CQS_ITER:
      if (value == null) {
        unsetDisableCqsIter();
      } else {
        setDisableCqsIter((java.lang.Boolean)value);
      }
      break;

    case DISABLE_VIS_ITER:
      if (value == null) {
        unsetDisableVisIter();
      } else {
        setDisableVisIter((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case READER_CLASS_NAME:
      return getReaderClassName();

    case READER_CLASS_OPTIONS:
      return getReaderClassOptions();

    case PUSH_DOWN_LIST:
      return getPushDownList();

    case PUSH_DOWN_LIST_OPTIONS:
      return getPushDownListOptions();

    case DISABLE_CFS_ITER:
      return isDisableCfsIter();

    case DISABLE_CQS_ITER:
      return isDisableCqsIter();

    case DISABLE_VIS_ITER:
      return isDisableVisIter();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case READER_CLASS_NAME:
      return isSetReaderClassName();
    case READER_CLASS_OPTIONS:
      return isSetReaderClassOptions();
    case PUSH_DOWN_LIST:
      return isSetPushDownList();
    case PUSH_DOWN_LIST_OPTIONS:
      return isSetPushDownListOptions();
    case DISABLE_CFS_ITER:
      return isSetDisableCfsIter();
    case DISABLE_CQS_ITER:
      return isSetDisableCqsIter();
    case DISABLE_VIS_ITER:
      return isSetDisableVisIter();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PushdownReaderRequest)
      return this.equals((PushdownReaderRequest)that);
    return false;
  }

  public boolean equals(PushdownReaderRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_readerClassName = true && this.isSetReaderClassName();
    boolean that_present_readerClassName = true && that.isSetReaderClassName();
    if (this_present_readerClassName || that_present_readerClassName) {
      if (!(this_present_readerClassName && that_present_readerClassName))
        return false;
      if (!this.readerClassName.equals(that.readerClassName))
        return false;
    }

    boolean this_present_readerClassOptions = true && this.isSetReaderClassOptions();
    boolean that_present_readerClassOptions = true && that.isSetReaderClassOptions();
    if (this_present_readerClassOptions || that_present_readerClassOptions) {
      if (!(this_present_readerClassOptions && that_present_readerClassOptions))
        return false;
      if (!this.readerClassOptions.equals(that.readerClassOptions))
        return false;
    }

    boolean this_present_pushDownList = true && this.isSetPushDownList();
    boolean that_present_pushDownList = true && that.isSetPushDownList();
    if (this_present_pushDownList || that_present_pushDownList) {
      if (!(this_present_pushDownList && that_present_pushDownList))
        return false;
      if (!this.pushDownList.equals(that.pushDownList))
        return false;
    }

    boolean this_present_pushDownListOptions = true && this.isSetPushDownListOptions();
    boolean that_present_pushDownListOptions = true && that.isSetPushDownListOptions();
    if (this_present_pushDownListOptions || that_present_pushDownListOptions) {
      if (!(this_present_pushDownListOptions && that_present_pushDownListOptions))
        return false;
      if (!this.pushDownListOptions.equals(that.pushDownListOptions))
        return false;
    }

    boolean this_present_disableCfsIter = true;
    boolean that_present_disableCfsIter = true;
    if (this_present_disableCfsIter || that_present_disableCfsIter) {
      if (!(this_present_disableCfsIter && that_present_disableCfsIter))
        return false;
      if (this.disableCfsIter != that.disableCfsIter)
        return false;
    }

    boolean this_present_disableCqsIter = true;
    boolean that_present_disableCqsIter = true;
    if (this_present_disableCqsIter || that_present_disableCqsIter) {
      if (!(this_present_disableCqsIter && that_present_disableCqsIter))
        return false;
      if (this.disableCqsIter != that.disableCqsIter)
        return false;
    }

    boolean this_present_disableVisIter = true;
    boolean that_present_disableVisIter = true;
    if (this_present_disableVisIter || that_present_disableVisIter) {
      if (!(this_present_disableVisIter && that_present_disableVisIter))
        return false;
      if (this.disableVisIter != that.disableVisIter)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetReaderClassName()) ? 131071 : 524287);
    if (isSetReaderClassName())
      hashCode = hashCode * 8191 + readerClassName.hashCode();

    hashCode = hashCode * 8191 + ((isSetReaderClassOptions()) ? 131071 : 524287);
    if (isSetReaderClassOptions())
      hashCode = hashCode * 8191 + readerClassOptions.hashCode();

    hashCode = hashCode * 8191 + ((isSetPushDownList()) ? 131071 : 524287);
    if (isSetPushDownList())
      hashCode = hashCode * 8191 + pushDownList.hashCode();

    hashCode = hashCode * 8191 + ((isSetPushDownListOptions()) ? 131071 : 524287);
    if (isSetPushDownListOptions())
      hashCode = hashCode * 8191 + pushDownListOptions.hashCode();

    hashCode = hashCode * 8191 + ((disableCfsIter) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((disableCqsIter) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((disableVisIter) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(PushdownReaderRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetReaderClassName(), other.isSetReaderClassName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReaderClassName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.readerClassName, other.readerClassName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReaderClassOptions(), other.isSetReaderClassOptions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReaderClassOptions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.readerClassOptions, other.readerClassOptions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPushDownList(), other.isSetPushDownList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPushDownList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pushDownList, other.pushDownList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPushDownListOptions(), other.isSetPushDownListOptions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPushDownListOptions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pushDownListOptions, other.pushDownListOptions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDisableCfsIter(), other.isSetDisableCfsIter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisableCfsIter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.disableCfsIter, other.disableCfsIter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDisableCqsIter(), other.isSetDisableCqsIter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisableCqsIter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.disableCqsIter, other.disableCqsIter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDisableVisIter(), other.isSetDisableVisIter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisableVisIter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.disableVisIter, other.disableVisIter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PushdownReaderRequest(");
    boolean first = true;

    sb.append("readerClassName:");
    if (this.readerClassName == null) {
      sb.append("null");
    } else {
      sb.append(this.readerClassName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("readerClassOptions:");
    if (this.readerClassOptions == null) {
      sb.append("null");
    } else {
      sb.append(this.readerClassOptions);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pushDownList:");
    if (this.pushDownList == null) {
      sb.append("null");
    } else {
      sb.append(this.pushDownList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pushDownListOptions:");
    if (this.pushDownListOptions == null) {
      sb.append("null");
    } else {
      sb.append(this.pushDownListOptions);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("disableCfsIter:");
    sb.append(this.disableCfsIter);
    first = false;
    if (!first) sb.append(", ");
    sb.append("disableCqsIter:");
    sb.append(this.disableCqsIter);
    first = false;
    if (!first) sb.append(", ");
    sb.append("disableVisIter:");
    sb.append(this.disableVisIter);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PushdownReaderRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PushdownReaderRequestStandardScheme getScheme() {
      return new PushdownReaderRequestStandardScheme();
    }
  }

  private static class PushdownReaderRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<PushdownReaderRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PushdownReaderRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // READER_CLASS_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.readerClassName = iprot.readString();
              struct.setReaderClassNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // READER_CLASS_OPTIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map130 = iprot.readMapBegin();
                struct.readerClassOptions = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map130.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key131;
                @org.apache.thrift.annotation.Nullable java.lang.String _val132;
                for (int _i133 = 0; _i133 < _map130.size; ++_i133)
                {
                  _key131 = iprot.readString();
                  _val132 = iprot.readString();
                  struct.readerClassOptions.put(_key131, _val132);
                }
                iprot.readMapEnd();
              }
              struct.setReaderClassOptionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PUSH_DOWN_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list134 = iprot.readListBegin();
                struct.pushDownList = new java.util.ArrayList<IterInfo>(_list134.size);
                @org.apache.thrift.annotation.Nullable IterInfo _elem135;
                for (int _i136 = 0; _i136 < _list134.size; ++_i136)
                {
                  _elem135 = new IterInfo();
                  _elem135.read(iprot);
                  struct.pushDownList.add(_elem135);
                }
                iprot.readListEnd();
              }
              struct.setPushDownListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PUSH_DOWN_LIST_OPTIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map137 = iprot.readMapBegin();
                struct.pushDownListOptions = new java.util.HashMap<java.lang.String,java.util.Map<java.lang.String,java.lang.String>>(2*_map137.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key138;
                @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> _val139;
                for (int _i140 = 0; _i140 < _map137.size; ++_i140)
                {
                  _key138 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TMap _map141 = iprot.readMapBegin();
                    _val139 = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map141.size);
                    @org.apache.thrift.annotation.Nullable java.lang.String _key142;
                    @org.apache.thrift.annotation.Nullable java.lang.String _val143;
                    for (int _i144 = 0; _i144 < _map141.size; ++_i144)
                    {
                      _key142 = iprot.readString();
                      _val143 = iprot.readString();
                      _val139.put(_key142, _val143);
                    }
                    iprot.readMapEnd();
                  }
                  struct.pushDownListOptions.put(_key138, _val139);
                }
                iprot.readMapEnd();
              }
              struct.setPushDownListOptionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DISABLE_CFS_ITER
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.disableCfsIter = iprot.readBool();
              struct.setDisableCfsIterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DISABLE_CQS_ITER
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.disableCqsIter = iprot.readBool();
              struct.setDisableCqsIterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DISABLE_VIS_ITER
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.disableVisIter = iprot.readBool();
              struct.setDisableVisIterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PushdownReaderRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.readerClassName != null) {
        oprot.writeFieldBegin(READER_CLASS_NAME_FIELD_DESC);
        oprot.writeString(struct.readerClassName);
        oprot.writeFieldEnd();
      }
      if (struct.readerClassOptions != null) {
        oprot.writeFieldBegin(READER_CLASS_OPTIONS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.readerClassOptions.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter145 : struct.readerClassOptions.entrySet())
          {
            oprot.writeString(_iter145.getKey());
            oprot.writeString(_iter145.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.pushDownList != null) {
        oprot.writeFieldBegin(PUSH_DOWN_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.pushDownList.size()));
          for (IterInfo _iter146 : struct.pushDownList)
          {
            _iter146.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.pushDownListOptions != null) {
        oprot.writeFieldBegin(PUSH_DOWN_LIST_OPTIONS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, struct.pushDownListOptions.size()));
          for (java.util.Map.Entry<java.lang.String, java.util.Map<java.lang.String,java.lang.String>> _iter147 : struct.pushDownListOptions.entrySet())
          {
            oprot.writeString(_iter147.getKey());
            {
              oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, _iter147.getValue().size()));
              for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter148 : _iter147.getValue().entrySet())
              {
                oprot.writeString(_iter148.getKey());
                oprot.writeString(_iter148.getValue());
              }
              oprot.writeMapEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DISABLE_CFS_ITER_FIELD_DESC);
      oprot.writeBool(struct.disableCfsIter);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DISABLE_CQS_ITER_FIELD_DESC);
      oprot.writeBool(struct.disableCqsIter);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DISABLE_VIS_ITER_FIELD_DESC);
      oprot.writeBool(struct.disableVisIter);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PushdownReaderRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PushdownReaderRequestTupleScheme getScheme() {
      return new PushdownReaderRequestTupleScheme();
    }
  }

  private static class PushdownReaderRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<PushdownReaderRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PushdownReaderRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetReaderClassName()) {
        optionals.set(0);
      }
      if (struct.isSetReaderClassOptions()) {
        optionals.set(1);
      }
      if (struct.isSetPushDownList()) {
        optionals.set(2);
      }
      if (struct.isSetPushDownListOptions()) {
        optionals.set(3);
      }
      if (struct.isSetDisableCfsIter()) {
        optionals.set(4);
      }
      if (struct.isSetDisableCqsIter()) {
        optionals.set(5);
      }
      if (struct.isSetDisableVisIter()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetReaderClassName()) {
        oprot.writeString(struct.readerClassName);
      }
      if (struct.isSetReaderClassOptions()) {
        {
          oprot.writeI32(struct.readerClassOptions.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter149 : struct.readerClassOptions.entrySet())
          {
            oprot.writeString(_iter149.getKey());
            oprot.writeString(_iter149.getValue());
          }
        }
      }
      if (struct.isSetPushDownList()) {
        {
          oprot.writeI32(struct.pushDownList.size());
          for (IterInfo _iter150 : struct.pushDownList)
          {
            _iter150.write(oprot);
          }
        }
      }
      if (struct.isSetPushDownListOptions()) {
        {
          oprot.writeI32(struct.pushDownListOptions.size());
          for (java.util.Map.Entry<java.lang.String, java.util.Map<java.lang.String,java.lang.String>> _iter151 : struct.pushDownListOptions.entrySet())
          {
            oprot.writeString(_iter151.getKey());
            {
              oprot.writeI32(_iter151.getValue().size());
              for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter152 : _iter151.getValue().entrySet())
              {
                oprot.writeString(_iter152.getKey());
                oprot.writeString(_iter152.getValue());
              }
            }
          }
        }
      }
      if (struct.isSetDisableCfsIter()) {
        oprot.writeBool(struct.disableCfsIter);
      }
      if (struct.isSetDisableCqsIter()) {
        oprot.writeBool(struct.disableCqsIter);
      }
      if (struct.isSetDisableVisIter()) {
        oprot.writeBool(struct.disableVisIter);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PushdownReaderRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.readerClassName = iprot.readString();
        struct.setReaderClassNameIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map153 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING); 
          struct.readerClassOptions = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map153.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key154;
          @org.apache.thrift.annotation.Nullable java.lang.String _val155;
          for (int _i156 = 0; _i156 < _map153.size; ++_i156)
          {
            _key154 = iprot.readString();
            _val155 = iprot.readString();
            struct.readerClassOptions.put(_key154, _val155);
          }
        }
        struct.setReaderClassOptionsIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list157 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.pushDownList = new java.util.ArrayList<IterInfo>(_list157.size);
          @org.apache.thrift.annotation.Nullable IterInfo _elem158;
          for (int _i159 = 0; _i159 < _list157.size; ++_i159)
          {
            _elem158 = new IterInfo();
            _elem158.read(iprot);
            struct.pushDownList.add(_elem158);
          }
        }
        struct.setPushDownListIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map160 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP); 
          struct.pushDownListOptions = new java.util.HashMap<java.lang.String,java.util.Map<java.lang.String,java.lang.String>>(2*_map160.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key161;
          @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> _val162;
          for (int _i163 = 0; _i163 < _map160.size; ++_i163)
          {
            _key161 = iprot.readString();
            {
              org.apache.thrift.protocol.TMap _map164 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING); 
              _val162 = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map164.size);
              @org.apache.thrift.annotation.Nullable java.lang.String _key165;
              @org.apache.thrift.annotation.Nullable java.lang.String _val166;
              for (int _i167 = 0; _i167 < _map164.size; ++_i167)
              {
                _key165 = iprot.readString();
                _val166 = iprot.readString();
                _val162.put(_key165, _val166);
              }
            }
            struct.pushDownListOptions.put(_key161, _val162);
          }
        }
        struct.setPushDownListOptionsIsSet(true);
      }
      if (incoming.get(4)) {
        struct.disableCfsIter = iprot.readBool();
        struct.setDisableCfsIterIsSet(true);
      }
      if (incoming.get(5)) {
        struct.disableCqsIter = iprot.readBool();
        struct.setDisableCqsIterIsSet(true);
      }
      if (incoming.get(6)) {
        struct.disableVisIter = iprot.readBool();
        struct.setDisableVisIterIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

